### ISSUE TITLE
Dependency vulnerabillity

### ISSUE THREAD

**Issue by tseboho** [Uber5/u5-derive#2]
I received a notification about a dependency vulnerability:
https://github.com/Uber5/u5-derive/network/dependencies
<img width="750" alt="screen shot 2018-04-29 at 12 12 59" src="https://user-images.githubusercontent.com/5609223/39405529-cee81732-4ba6-11e8-8f2e-fd2a9298255c.png">

**Comment by Chris927** [comment]
Thanks! I got it, too.

Cheers,
Chris
